exclude: ["README.md", "_blogscripts"]

title : joshuamorton
author :
  name : Joshua Morton
  github : github.com/joshuamorton

url: "joshuamorton.github.io"
github_url: "https://github.com/joshuamorton/joshuamorton.github.com/blob/master/"

markdown: rdiscount
permalink: pretty
highlighter: pygments
