exclude: ["README.md"]

title : Joshuamorton
author :
  name : Joshua Morton
  github : github.com/joshuamorton

url: "joshuamorton.github.io"

markdown: rdiscount
permalink: pretty
highlighter: pygments
