# Site settings
title: Joshua Morton
subtitle: portfolio and blog
email: joshua.morton13@gmail.com
description: A personal website and blog for Joshua Morton.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joshuamorton.github.io" # the base hostname & protocol for your site
author: Joshua Morton

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/joshuamorton
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/joshuamorton13
pinterest_url:
slack_url:
twitter_url: https://twitter.com/joshthejuggles

blog_github_url: "https://github.com/joshuamorton/joshuamorton.github.com/blob/master/"
blog_python_url: "https://github.com/joshuamorton/joshuamorton.github.com/blob/master/_blogscripts/"

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    highlighter: rouge

exclude: ["README.md", "_blogscripts"]

permalink: pretty
paginate: 1
paginate_path: "blog/page/:num"

collections:
    projects:
        output: true
        permalink: /projects/:path/
    experience:
        output: true
        permalink: /experience/:path/
    involvement:
        output: true
        permalink: /involvement/:path/

gems:
    - jekyll-paginate
