exclude: ["README.md", "_blogscripts"]

title : joshuamorton
author :
  name : Joshua Morton
  github : github.com/joshuamorton

url: "joshuamorton.github.io"
github_url: "https://github.com/joshuamorton/joshuamorton.github.com/blob/master/"
python_url: "https://github.com/joshuamorton/joshuamorton.github.com/blob/master/_blogscripts/"


markdown: redcarpet

kramdown:
    input: GFM

permalink: pretty
highlighter: pygments
paginate: 2
paginator_path: "blog/page:num"
